config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts
  post '/posts/:post_id/comments' => 'comments#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Post.find(params[:post_id]).comments.new(comment_params)
    @comment.save
    redirect_to :back
  end

  private
  def comment_params
    params.permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.reverse
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to "/"
  end

  def show
    @comments = @post.comments
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  def destroy
    @post.destroy
    redirect_to "/"
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoardGem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
  <%if user_signed_in?%>
    <p>
      <%= current_user.email%>
    </p>
    <!-- <a href="/users/sign_out" data-method="delete">로그아웃</a> -->
    <%=link_to '로그아웃', destroy_user_session_path, method: :delete%>
  <%else%>
    <%= link_to '로그인', new_user_session_path%>
    <%= link_to '회원가입', new_user_registration_path%>
    <!-- <a href="/users/sign_in">로그인</a>
    <a href="/users/sign_up">회원가입</a> -->
  <%end%>
  <div class="container">

    <%= yield %>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

app/views/posts/_form.html.erb
<!-- <%= form_for @post do |f| %>
  <%= f.text_field :title%>
  <%= f.text_area :content%>
  <%= f.submit%>
<%end%> -->

<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :content%>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1>수정해</h1>
<%= render 'form'%>

<!-- <form action="/posts/<%=@post.id%>" method="post">
  <input type="text" name="title" value="<%=@post.title%>"/> <br />
  <textarea name="content"><%=@post.content%></textarea> <br />
  <input type="hidden" name="_method" value="put" />
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="submit" />
</form>

<%= form_tag("/posts/#{@post.id}", method: 'put') do%>
  <%= label_tag(:title, "title:") %>
  <%= text_field_tag :title, @post.title %>
  <%= label_tag(:content, "content:" ) %>
  <%= text_area_tag(:content, @post.content, size: "24x6") %>
  <%= submit_tag("submit") %>
<%end%> -->

app/views/posts/index.html.erb
<a href="/posts/new">글 쓰러가기</a>
<%= link_to '글 쓰기', new_post_path%>
<% @posts.each do |post| %>
  <p><%= post.id %></p>
  <p><%= post.title %></p>
  <p><%= post.content %></p>
  <a href="/posts/<%=post.id%>">글 보러가기</a>
  <%= link_to '글보기', post%>
  <hr />
<% end %>

app/views/posts/new.html.erb
<h1>글 써</h1>
<%= render 'form'%>
<!-- 
<form action="/posts" method="post">
  <input type="text" name="title" /> <br />
  <textarea name="content"></textarea> <br />
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="submit" />
</form>

<%= form_tag('/posts',method: 'post') do%>
  <%= label_tag(:title, "title:") %>
  <%= text_field_tag :title%>
  <%= label_tag(:content, "content:") %>
  <%= text_area_tag(:content, size: "60x12") %>
  <%= submit_tag("submit") %>
<%end%> -->

app/views/posts/show.html.erb
<h1>글 봐!!</h1>
<%= @post.id %>번째 글
<%= @post.title %>
<%= @post.content %>

<%= link_to '수정하기', edit_post_path(@post) %>
<%= link_to '삭제하기', @post, method: :delete, data: {confirm: '너 지울거야?'} %>
<a href="/posts/<%= @post.id %>/edit">수정하기</a>
<a href="/posts/<%= @post.id %>" data-method="delete" data-confirm="삭제할래?">삭제하기</a>
<hr />

<form action="/posts/<%= @post.id%>/comments" method="post">
  <input type="text" name="content" /><br />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" />
</form>
<hr />

<% @comments.each do |comment| %>
  <%= comment.content %>
  <hr />
<% end %>